# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='部门名称')),
                ('super_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='权限名称')),
                ('type', models.CharField(max_length=256, verbose_name='权限类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.CharField(max_length=256, unique=True, verbose_name='工号')),
                ('username', models.CharField(max_length=256, verbose_name='员工姓名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Department')),
                ('superior', models.ManyToManyField(blank=True, null=True, related_name='_user_superior_+', to='framework.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_authorized', models.BooleanField(default=False)),
                ('authorize_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('authorizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizer', to='framework.User')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='position',
            name='users',
            field=models.ManyToManyField(through='framework.UserPosition', to='framework.User'),
        ),
        migrations.AddField(
            model_name='permission',
            name='position',
            field=models.ManyToManyField(to='framework.Position'),
        ),
    ]
