# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='superior',
            field=models.ManyToManyField(related_name='_user_superior_+', to='framework.User'),
        ),
    ]
